"""
training/create_modelfile.py — Generate Ollama Modelfile for Baby.

Creates a Modelfile that wraps the fine-tuned LoRA adapter
for use with Ollama.

Usage:
    python training/create_modelfile.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELFILE_PATH = ROOT / "training" / "Modelfile"
GGUF_PATH = ROOT / "training" / "models" / "Baby-lora.gguf"

# Baby's system prompt
SYSTEM_PROMPT = """You are Baby ("Baby"), a warm, emotionally-intelligent desktop assistant created for your user. You help with daily tasks, answer questions, and provide companionship. You use tools when needed (file operations, web search, math calculations, screen control). You are concise, friendly, and speak naturally — not robotically. You call the user by their preferred name and remember details from past conversations. You are running locally on their desktop as a personal AI assistant."""

MODELFILE_TEMPLATE = f'''# Ollama Modelfile for Baby (Fine-tuned)
# Generated by training/create_modelfile.py

# Base model (update path if using different quantization)
FROM ./models/Baby-lora.gguf

# System prompt
SYSTEM """{SYSTEM_PROMPT}"""

# Template for ChatML format (Llama 3.1 compatible)
TEMPLATE """{{{{- if .System }}}}<|start_header_id|>system<|end_header_id|>

{{{{ .System }}}}<|eot_id|>{{{{- end }}}}<|start_header_id|>user<|end_header_id|>

{{{{ .Prompt }}}}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{{{{ .Response }}}}<|eot_id|>"""

# Model parameters
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER repeat_penalty 1.1
PARAMETER num_predict 512

# Stop tokens
PARAMETER stop "<|eot_id|>"
PARAMETER stop "<|end_header_id|>"
'''


def main():
    print("=" * 50)
    print("Baby Ollama Modelfile Generator")
    print("=" * 50)
    
    if not GGUF_PATH.exists():
        print(f"\nWarning: GGUF model not found at {GGUF_PATH}")
        print("Run training first: python training/train_ollama.py")
        print("\nGenerating Modelfile anyway (update path later)...\n")
    
    # Write Modelfile
    MODELFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(MODELFILE_PATH, "w", encoding="utf-8") as f:
        f.write(MODELFILE_TEMPLATE)
    
    print(f"Modelfile created: {MODELFILE_PATH}")
    print("\nTo build the Ollama model:")
    print(f"  cd {ROOT}")
    print(f"  ollama create Baby -f training/Modelfile")
    print("\nTo test:")
    print(f"  ollama run Baby")


if __name__ == "__main__":
    main()



















